### ISSUE TITLE
Specified cast is not valid.

### ISSUE THREAD

**Issue by ah394496** [RetroDriven/Pocket_Updater#70] opened 2023-07-17 04:18 UTC
Hello,
When I try to change which cores I would like to keep/update, the app does not allow me to make changes to the list. If I toggle on all of them, the app works as it should and checks/updates them all. But if I go in and uncheck some, I am not permitted to save my changes and am told 'Specified cast is not valid'. Am I doing something wrong? I am using the latest version on a PC running Windows 10.
My thanks,
Andy

**Comment by frozenwizard** [comment] 2023-08-18 22:22
I had the same issue.  After installing things to the pocket and restarting the app, I did not get that error afterwards.

**Comment by ah394496** [comment] 2023-08-19 04:47
Thanks for the suggestion, on my end I finally got the message to go away. In the list of cores I was trying to check or uncheck many at once. The app didn't like that. But if I did it one at a time, saving after each time, it seemed to work.    On Friday, August 18, 2023 at 06:22:59 PM EDT, frozenwizard ***@***.***> wrote:  
 
 


I had the same issue. After installing things to the pocket and restarting the app, I did not get that error afterwards.

**Comment by RetroDriven** [comment] 2023-09-08 02:48
Is this still happening with v1.5.7?

**Comment by ah394496** [comment] 2023-09-08 07:11
Hello,
It's not happening if I select cores one at a time. So I have ten that I no longer wish to have, I have to uncheck one, save, uncheck one, save, etc. If I try to do this in a batch manner, that's when I get the error.
Andy
    On Thursday, September 7, 2023 at 10:48:37 PM EDT, RetroDriven ***@***.***> wrote:  
 
 


Is this still happening with v1.5.7?

**Comment by jzrola** [comment] 2023-09-23 20:15
I have the same problem. My workaround was to manually change the skip element from true to false or vice versa.

**Comment by ah394496** [comment] 2023-09-24 10:12
Interesting. I appreciate you getting back to me on this. A couple nights ago I updated my Pocket with Updater. Jotego's Sega16 core was added. Have you tried that one yet? It loads, but any time I select a game within the emulator, I'm met with a Patreon nag screen I can't get rid of. I was curious if you've seen that as well. I don't know how to get around it. I wrote to him via Twitter (X), but no response.
Andy
    On Saturday, September 23, 2023 at 04:15:52 PM EDT, jzrola ***@***.***> wrote:  
 
 


I have the same problem. My workaround was to manually change the skip element from true to false or vice versa.

**Comment by ah394496** [comment] 2023-10-01 07:46
Quick update, the new version of the Sega16 core has the Patreon nag screen removed. The new Teenage Mutant Ninja Turtles core, however, did have a nag screen and I can't figure out how to turn it off. Thanks for all you do, it's appreciated
    On Sunday, September 24, 2023 at 06:12:18 AM EDT, Andrew Holland ***@***.***> wrote:  
 
  Interesting. I appreciate you getting back to me on this. A couple nights ago I updated my Pocket with Updater. Jotego's Sega16 core was added. Have you tried that one yet? It loads, but any time I select a game within the emulator, I'm met with a Patreon nag screen I can't get rid of. I was curious if you've seen that as well. I don't know how to get around it. I wrote to him via Twitter (X), but no response.
Andy
    On Saturday, September 23, 2023 at 04:15:52 PM EDT, jzrola ***@***.***> wrote:  
 
 


I have the same problem. My workaround was to manually change the skip element from true to false or vice versa.

**Comment by ivodopiviz** [comment] 2023-10-22 15:17
This error is because the DataGrid cells seem to have a string value instead of boolean in some cases, but I haven't been able to reproduce why. A faster repro case is to click quickly the same checkbox over and over until you crash the app. At least it crashes to the debugger instead of giving you the cryptic message box.

**Comment by ah394496** [comment] 2023-10-22 17:40
I appreciate you sticking with this.Some of the recent joetgo cores added in the app have nag screens that won't go away... do you know how to turn them off? Looks like Patreon credits or something
    On Sunday, October 22, 2023 at 11:17:35 AM EDT, Ivan Vodopiviz ***@***.***> wrote:  
 
 


This error is because the DataGrid cells seem to have a string value instead of boolean in some cases, but I haven't been able to reproduce why. A faster repro case is to click quickly the same checkbox over and over until you crash the app. At least it crashes to the debugger instead of giving you the cryptic message box.

**Comment by RetroDriven** [comment] 2024-05-12 03:11
This should be resolved with v1.6.1

**Closed by RetroDriven** 2024-05-12 03:11 UTC
