### ISSUE TITLE
Issues managing cores

### ISSUE THREAD

**Issue by Leeberator** [RetroDriven/Pocket_Updater#56] opened 2023-02-24 17:53 UTC
I cannot deselect individual cores from the Manage Cores tab. Individual core checkboxes do not respond to single-clicking, only double-clicking - and when the core is clicked away from (by clicking on another core, changing tabs in the program, etc.), the checkbox reverts to the checked state. Checking/unchecking all cores works as expected.

Upon unchecking all via the checkbox at the top, I was able to successfully save and deselect all cores. Now, however, I am unable to save a new selection of cores.  Checking the boxes next to the desired individual cores and then clicking Save throws an error and the selections are not saved. Restarting the application confirms the selections do not save.

I've deleted the config file and started fresh, yet experience the same behavior. This occurs on the latest release as well as the previous.

<img width="673" alt="Screenshot 2023-02-24 125227" src="https://user-images.githubusercontent.com/26010345/221253227-9f1b86c0-754f-44e6-a0d7-2816b5402186.png">

**Comment by RetroDriven** [comment] 2023-02-25 00:03
I'm hoping the issue is fixed in v1.5.2. Give that a test please.

**Closed** 2023-02-25 04:38 UTC
